CREATE TABLE [catalogo].[PRODUCTO]
(
[NUMPRODUCTO] [int] NOT NULL,
[NOMBREPRODUCTO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPPRODUCTO] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMEXISTENCIAS] [int] NULL
) ON [Secundario]
GO
ALTER TABLE [catalogo].[PRODUCTO] ADD CONSTRAINT [Unique_Identifier4] PRIMARY KEY CLUSTERED ([NUMPRODUCTO]) ON [Secundario]
GO
